name: Update M3U Files

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行一次
  workflow_dispatch:  # 手动触发

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch M3U files
      run: |
        curl -v -o IPV6.m3u https://mirror.ghproxy.com/https://raw.githubusercontent.com/Ftindy/IPTV-URL/main/IPV6.m3u
        curl -v -o IPTV.m3u https://mirror.ghproxy.com/https://raw.githubusercontent.com/Ftindy/IPTV-URL/main/IPTV.m3u

    - name: Combine M3U files into a single TXT file
      run: |
        cat IPV6.m3u IPTV.m3u > combined_iptv.txt

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add combined_iptv.txt
        git commit -m 'Update combined_iptv.txt' || echo "No changes to commit"
        git push || echo "Push failed"
